root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  nexus: features/integrations/private-registry-gatekeeper-plugins/nexus-repository-manager-gatekeeper-plugin.md
  artifactory: features/integrations/private-registry-gatekeeper-plugins/artifactory-gatekeeper-plugin-overview.md
  fix-images: products/snyk-container/getting-around-the-snyk-container-ui/analysis-and-remediation-for-your-images-from-the-snyk-app.md
  languages: more-info/product-language-support-list.md
  snyk-infrastructure-as-code/detecting-infrastructure-as-code-files-using-a-broker: features/snyk-broker/snyk-broker-infrastructure-as-code-detection/detecting-kubernetes-configuration-files-using-a-broker.md
  features/integrations/ci-cd-integrations/snyk-cicd-integration-good-practices: features/integrations/ci-cd-integrations/README.md
  products/snyk-infrastructure-as-code/snyk-cli-for-infrastructure-as-code: products/snyk-open-source/language-and-package-manager-support/README.md
  getting-started/snyk-cicd-integration-good-practices: features/integrations/ci-cd-integrations/README.md
  features/integrations/snyk-broker: features/snyk-broker/README.md
