root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  nexus: features/integrations/private-registry-gatekeeper-plugins/nexus-repository-manager-gatekeeper-plugin.md
  artifactory: features/integrations/private-registry-gatekeeper-plugins/artifactory-gatekeeper-plugin-overview.md
  fix-images: products/snyk-container/getting-around-the-snyk-container-ui/analysis-and-remediation-for-your-images-from-the-snyk-app.md
  snyk-cli/guides-for-our-cli/cli-reference: features/snyk-cli/cli-reference/README.md